<?xml version="1.0" encoding="UTF-8"?>
<!-- añadidos espacios en blanco en etiquetas 'xml' ' !ELEMENT' y '!ATTLIST' -->
<!-- modificado elemento raiz softwareLibre para contener 'programas' y 'licencias'
     sustituidos elementos 'aplicaciones' y 'aplicacion' por 'programas' y 'programa'
     añadido elemento 'nombre'
     sustituido #REQUIRED por #IMPLIED de elemento 'fechaPublicacion'
     sustituido 'ID' por 'CDATA' en '!ATTLIST licencia nombre' -->
<!DOCTYPE softwareLibre [
  <!ELEMENT softwareLibre (programas, licencias)>
  <!ELEMENT licencias (licencia*)>
  <!ELEMENT licencia EMPTY>
  <!ELEMENT programas (programa*)>
  <!ELEMENT programa (nombre+, version*)>
  <!ELEMENT version EMPTY>
  <!ELEMENT nombre ANY>
  <!ATTLIST licencia nombre CDATA #REQUIRED>
  <!ATTLIST aplicacion nombre NMTOKEN #REQUIRED>
  <!ATTLIST version nombre NMTOKEN #REQUIRED>
  <!ATTLIST version licencia CDATA #REQUIRED>
  <!ATTLIST version fechaPublicacion CDATA #IMPLIED>
]>
<!-- eliminados caracteres '>' sobrantes
     añadidos espacios en blanco-->
  <softwareLibre>
    <programas>
        <programa>
            <nombre>Inkscape</nombre>
            <version nombre="0.47" licencia="GPL v2" fechaPublicacion="17/08/2010"/>
            <version nombre="0.48" licencia="GPL v2" fechaPublicacion="17/08/2010"/>
            <version nombre="0.48.2" licencia="GPL v2" fechaPublicacion="14/08/2011"/>
        </programa>
        <programa>
        <nombre>PostgreSQL</nombre>
            <version nombre="9.1.0" licencia="BSD2" fechaPublicacion="15/09/2011"/>
            <version nombre="9.1.3" licencia="BSD2"/>
        </programa>
    </programas>
    <licencias>
        <licencia nombre="GPL v2"/>
        <licencia nombre="BSD2"/>
        <licencia nombre="Apache v2"/>
    </licencias>
</softwareLibre>